<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-15T19:14:15 IST" name="Suite" finished-at="2022-12-15T19:14:41 IST" duration-ms="26283">
    <groups>
    </groups>
    <test started-at="2022-12-15T19:14:15 IST" name="Test" finished-at="2022-12-15T19:14:41 IST" duration-ms="26283">
      <class name="TestCases.LoginTestCase">
        <test-method is-config="true" signature="launch()[pri:0, instance:TestCases.LoginTestCase@2ef3eef9]" started-at="2022-12-15T19:14:15 IST" name="launch" finished-at="2022-12-15T19:14:21 IST" duration-ms="5946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="Method1()[pri:0, instance:TestCases.LoginTestCase@2ef3eef9]" started-at="2022-12-15T19:14:21 IST" name="Method1" finished-at="2022-12-15T19:14:22 IST" duration-ms="594" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Please check your username password. If you still can't log in, contact your Salesforce administrator.] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please check your username password. If you still can't log in, contact your Salesforce administrator.] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Resources.CommonMethods.AssertionMethod(CommonMethods.java:30)
at TestCases.LoginTestCase.Method1(LoginTestCase.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method1 -->
      </class> <!-- TestCases.LoginTestCase -->
      <class name="TestCases.SignUpTestCase">
        <test-method is-config="true" signature="launch()[pri:0, instance:TestCases.SignUpTestCase@661972b0]" started-at="2022-12-15T19:14:22 IST" name="launch" finished-at="2022-12-15T19:14:25 IST" duration-ms="3376" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="verifysignup()[pri:0, instance:TestCases.SignUpTestCase@661972b0]" started-at="2022-12-15T19:14:25 IST" name="verifysignup" finished-at="2022-12-15T19:14:41 IST" duration-ms="16322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifysignup -->
      </class> <!-- TestCases.SignUpTestCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
